### ISSUE TITLE
niepotrzebny folder

### ISSUE THREAD

**Issue by Magdalena-Nowak** [Magdalena-Nowak/team2#8]
Do usunięcia folder carousel wewnątrz img
Zmiana font family i font size na te które są zadeklarowane w zmiennych

**Comment by tsurdy** [comment]
- Usunięte nie potrzebne foldery ( robiłem o nocy i przypadkowo wkleiłem razem z zdjęciami )
- Zmienione font-family i font-size na wartości z zmiennych
